spring:
  application:
    name: spring-s3-upload

  servlet:
    multipart:
      max-file-size: 2GB
      max-request-size: 10GB

management:
  endpoints:
    web:
      exposure:
        include: prometheus
server:
  tomcat:
    threads:
      max: 200
    accept-count: 100
