spring:
  application:
    name: spring-s3-upload

  servlet:
    multipart:
      max-file-size: 2GB
      max-request-size: 10GB

server:
  tomcat:
    threads:
      max: 300
    mbeanregistry:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: prometheus
